#!/usr/bin/ruby
require 'sqlite3'

USAGE = <<EOS
usage: papet [--help] <command> [<args>]

Record when you work during the day.

Commands:
  start start the clock
  stop  stop the clock
  show  display all saved intervals
  clear delete all saved intervals
  copy  copy all saved intervals into the clipboard
EOS
DB_DIR = '.papet'
DB_FILE = 'intervals.db'
DATE_DB_FORMAT = '%Y%m%d'
DATE_PRINT_FORMAT = '%b %d, %Y'
TIME_DB_FORMAT = '%H:%M'
TIME_PRINT_FORMAT = '%I:%M %p'

def format_db_date(db_date_str)
  return '' if db_date_str.nil?
  Date.strptime(db_date_str, DATE_DB_FORMAT).strftime(DATE_PRINT_FORMAT)
end

def format_db_time(db_time_str)
  return '' if db_time_str.nil?
  Time.strptime(db_time_str, TIME_DB_FORMAT).strftime(TIME_PRINT_FORMAT)
end

def show_usage
  puts USAGE
end

def setup_db
  Dir.chdir(ENV['HOME'])
  Dir.mkdir(DB_DIR) if !File::exists?(DB_DIR)
  Dir.chdir(DB_DIR)
  db_exists = File::exists?(DB_FILE)
  db = SQLite3::Database.new DB_FILE

  if db_exists
    db.execute(<<-SQL) do |last_row|
      select * from intervals
      order by rowid desc
      limit 1;
    SQL
      # TODO: handle a forgotten punch out
    end
  else
    db.execute <<-SQL
      create table intervals (
        date  date,
        start time,
        end   time
      );
    SQL
  end

  db
end

def punch_in(db)
  db.execute(<<-SQL) do |last_interval|
    select start, end from intervals
    order by rowid desc
    limit 1;
  SQL
    if last_interval[1].nil?
      puts "You already punched in at #{format_db_time(last_interval[0])}"
      return
    end
  end

  now = Time.now
  db.execute <<-SQL, now.strftime(DATE_DB_FORMAT), now.strftime(TIME_DB_FORMAT)
    insert into intervals (date, start)
    values (?, ?);
  SQL

  puts "Punched in at #{now.strftime(TIME_PRINT_FORMAT)}"
end

def punch_out(db)
  start_time = ''

  db.execute(<<-SQL) do |last_interval|
    select start, end from intervals
    order by rowid desc
    limit 1;
  SQL
    last_interval = last_interval.map(&method(:format_db_time))
    start_time = last_interval.first
    unless last_interval[1].empty?
      puts "You already punched out at #{last_interval[1]}"
      return
    end
  end

  end_time = Time.now
  db.execute <<-SQL, end_time.strftime(TIME_DB_FORMAT)
    update intervals
    set end = ?
    order by rowid desc
    limit 1;
  SQL

  puts "Worked from #{start_time} - #{end_time.strftime(TIME_PRINT_FORMAT)}"
end

def show_intervals(db)
  dates = db.execute <<-SQL
    select distinct date from intervals
    order by date asc;
  SQL
  dates.each do |db_date|
    # TODO: show total hours worked
    puts format_db_date(db_date.first.to_s)

    db.execute(<<-SQL, db_date) do |interval|
      select start, end from intervals
      where date = ?
      order by start;
    SQL
      interval = interval.map(&method(:format_db_time))
      puts "#{interval[0]} - #{interval[1]}"
    end
  end
end

def clear_intervals(db)
  db.execute 'delete from intervals;'
  puts 'Cleared all intervals'
end

def clipboard(db, opts)
end

args = ARGV.map(&:dup)

if args.length == 0 || args[0] == '--help'
  show_usage
  Process.exit
end

db = setup_db

command = args.shift
case command
when 'start'  then punch_in(db)
when 'stop'   then punch_out(db)
when 'show'   then show_intervals(db)
when 'clear'  then clear_intervals(db)
when 'copy'   then clipboard(db, args)
else show_usage
end
